pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url "https://repo.itextsupport.com/releases" }
    }
}
rootProject.name = "PDFpro"
include ':app'
